import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from '../components/theme-provider';
import Navbar from '../components/ui/NavBar';
import { Toaster } from '../components/ui/toaster';
import { AuthProvider } from '../context/AuthContext';
import SocketManager from '../components/SocketManager';
import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar/>
              {children}
            <Toaster/>
            <SocketManager/>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
